/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csa_fppbo1;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS TUF
 */
public class MenuLihatJadwal extends javax.swing.JFrame {
    private String npm;
    private String nama;
    private String hari;
    
    public MenuLihatJadwal() {
        initComponents();
    }
    
    public MenuLihatJadwal(String nama, String npm){
        this.nama = nama;
        this.npm = npm;
        this.hari = hari;
        initComponents();
        // Setel teks label dengan nama yang diterima
        jLabel2.setText("Selamat datang, " + nama);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSenin = new javax.swing.JButton();
        jButtonKamis = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonRabu = new javax.swing.JButton();
        jButtonSelasa = new javax.swing.JButton();
        jButtonJumat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSenin.setBackground(new java.awt.Color(218, 218, 218));
        jButtonSenin.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonSenin.setText("Senin");
        jButtonSenin.setBorder(null);
        jButtonSenin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeninActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSenin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 200, 80));

        jButtonKamis.setBackground(new java.awt.Color(218, 218, 218));
        jButtonKamis.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonKamis.setText("Kamis");
        jButtonKamis.setBorder(null);
        jButtonKamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKamisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonKamis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 200, 80));

        jButton4.setBackground(new java.awt.Color(218, 218, 218));
        jButton4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton4.setText("Kembali");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 628, 60, 20));

        jButtonRabu.setBackground(new java.awt.Color(218, 218, 218));
        jButtonRabu.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonRabu.setText("Rabu");
        jButtonRabu.setBorder(null);
        jButtonRabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRabuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRabu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 190, 80));

        jButtonSelasa.setBackground(new java.awt.Color(218, 218, 218));
        jButtonSelasa.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonSelasa.setText("Selasa");
        jButtonSelasa.setBorder(null);
        jButtonSelasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelasaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSelasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 237, 200, 80));

        jButtonJumat.setBackground(new java.awt.Color(218, 218, 218));
        jButtonJumat.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButtonJumat.setText("Jumat");
        jButtonJumat.setBorder(null);
        jButtonJumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJumatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJumat, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 190, 80));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Menu Lihat Kelas.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeninActionPerformed
        // TODO add your handling code here:
        LihatJadwal lihatJadwal = new LihatJadwal(nama, npm, "Senin");
        lihatJadwal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonSeninActionPerformed

    private void jButtonKamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKamisActionPerformed
        // TODO add your handling code here:
        LihatJadwal lihatJadwal = new LihatJadwal(nama, npm, "Kamis");
        lihatJadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonKamisActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HalamanUtama hu = new HalamanUtama(nama, npm);
        hu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonRabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRabuActionPerformed
        // TODO add your handling code here:
        LihatJadwal lihatJadwal = new LihatJadwal(nama, npm, "Rabu");
        lihatJadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRabuActionPerformed

    private void jButtonSelasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelasaActionPerformed
        // TODO add your handling code here:
        LihatJadwal lihatJadwal = new LihatJadwal(nama, npm, "Selasa");
        lihatJadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSelasaActionPerformed

    private void jButtonJumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJumatActionPerformed
        // TODO add your handling code here:
        LihatJadwal lihatJadwal = new LihatJadwal(nama, npm, "Jumat");
        lihatJadwal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonJumatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLihatJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLihatJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLihatJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLihatJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLihatJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonJumat;
    private javax.swing.JButton jButtonKamis;
    private javax.swing.JButton jButtonRabu;
    private javax.swing.JButton jButtonSelasa;
    private javax.swing.JButton jButtonSenin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
