/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csa_fppbo1;

import java.sql.*;
import javax.swing.JOptionPane;
import database.dbconnection;
/**
 *
 * @author ASUS TUF
 */
    public class TambahJadwal extends javax.swing.JFrame {
        private String npm;
        private String nama;
    
    public TambahJadwal() {
        initComponents();
    }

    public TambahJadwal(String nama,String npm) {
        this.nama = nama;
        this.npm = npm;
        initComponents();
        // Setel teks label dengan nama yang diterima
        jLabel1.setText("Selamat datang, " + nama);
                }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButtonSimpanMatkul = new javax.swing.JButton();
        jTextFieldJam = new javax.swing.JTextField();
        jTextFieldMataKuliah = new javax.swing.JTextField();
        jTextFieldHari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(218, 218, 218));
        jButton4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton4.setText("Kembali");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 632, 60, 20));

        jButtonSimpanMatkul.setBackground(new java.awt.Color(218, 218, 218));
        jButtonSimpanMatkul.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButtonSimpanMatkul.setText("Simpan");
        jButtonSimpanMatkul.setBorder(null);
        jButtonSimpanMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanMatkulActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpanMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 483, 80, 20));

        jTextFieldJam.setBackground(new java.awt.Color(218, 218, 218));
        jTextFieldJam.setBorder(null);
        getContentPane().add(jTextFieldJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 405, 300, 20));

        jTextFieldMataKuliah.setBackground(new java.awt.Color(218, 218, 218));
        jTextFieldMataKuliah.setBorder(null);
        jTextFieldMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMataKuliahActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMataKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 300, 20));

        jTextFieldHari.setBackground(new java.awt.Color(218, 218, 218));
        jTextFieldHari.setBorder(null);
        getContentPane().add(jTextFieldHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 277, 300, 20));

        jLabel1.setBackground(new java.awt.Color(218, 218, 218));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 280, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Tambah Kelas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HalamanUtama hu = new HalamanUtama(nama, npm);
        hu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonSimpanMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanMatkulActionPerformed
        // TODO add your handling code here:
        String hari = jTextFieldHari.getText();
        String mataKuliah = jTextFieldMataKuliah.getText();
        String jam = jTextFieldJam.getText();

        try {
            dbconnection koneksi = new dbconnection();
            Connection conn = koneksi.getConnection();

            String insertSql = "INSERT INTO schedule (hari, mata_kuliah, jam, npm) VALUES (?, ?, ?, ?)";
            PreparedStatement insertStmt = conn.prepareStatement(insertSql);
            insertStmt.setString(1, hari);
            insertStmt.setString(2, mataKuliah);
            insertStmt.setString(3, jam);
            insertStmt.setString(4, npm);
            insertStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Jadwal berhasil disimpan!");

            // Setelah menyimpan, kembali ke halaman utama
            HalamanUtama hu = new HalamanUtama(nama, npm);
            hu.setVisible(true);
            this.setVisible(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonSimpanMatkulActionPerformed

    private void jTextFieldMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMataKuliahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMataKuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonSimpanMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldHari;
    private javax.swing.JTextField jTextFieldJam;
    private javax.swing.JTextField jTextFieldMataKuliah;
    // End of variables declaration//GEN-END:variables
}
